name: OpenWiXR-Renderer

on:
  workflow_dispatch:
  push:
    paths:
      - 'owxr/**'
      - '.github/workflows/owxr.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'owxr/**'
      - '.github/workflows/owxr.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CI_TOKEN }}
        submodules: true
    
    - name: Setup Environment
      run: | 
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
        
    - name: Build All
      run: |
        make all PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_21
